// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `BaskiConnection`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=ALEXANDERP;Initial Catalog=Baski;Integrated Security=True`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Baski.Orm.Models
{
    /// <summary>
    /// A class which represents the Player table.
    /// </summary>
	[Table("Player")]
	public partial class Player
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Firstname { get; set; }
		public virtual string LastName { get; set; }
		public virtual DateTime Birthdate { get; set; }
		public virtual int? Height { get; set; }
		public virtual int? Weight { get; set; }
		public virtual string Position { get; set; }
		public virtual string Description { get; set; }
		public virtual string ImageUrl { get; set; }
	}

    /// <summary>
    /// A class which represents the sysdiagrams table.
    /// </summary>
	[Table("sysdiagrams")]
	public partial class sysdiagram
	{
		public virtual string name { get; set; }
		public virtual int principal_id { get; set; }
		[Key]
		public virtual int diagram_id { get; set; }
		public virtual int? version { get; set; }
		public virtual byte[] definition { get; set; }
	}

    /// <summary>
    /// A class which represents the Social table.
    /// </summary>
	[Table("Social")]
	public partial class Social
	{
		[Key]
		public virtual long Id { get; set; }
		public virtual int PlayerId { get; set; }
		public virtual int SocialTypeId { get; set; }
		public virtual string Url { get; set; }
	}

    /// <summary>
    /// A class which represents the vw_aspnet_WebPartState_Paths view.
    /// </summary>
	[Table("vw_aspnet_WebPartState_Paths")]
	public partial class vwaspnetWebPartStatePath
	{
		public virtual Guid ApplicationId { get; set; }
		public virtual Guid PathId { get; set; }
		public virtual string Path { get; set; }
		public virtual string LoweredPath { get; set; }
	}

    /// <summary>
    /// A class which represents the vw_aspnet_WebPartState_Shared view.
    /// </summary>
	[Table("vw_aspnet_WebPartState_Shared")]
	public partial class vwaspnetWebPartStateShared
	{
		public virtual Guid PathId { get; set; }
		public virtual int? DataSize { get; set; }
		public virtual DateTime LastUpdatedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the SocialType table.
    /// </summary>
	[Table("SocialType")]
	public partial class SocialType
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int Title { get; set; }
		public virtual string ShortendTitle { get; set; }
	}

    /// <summary>
    /// A class which represents the vw_aspnet_WebPartState_User view.
    /// </summary>
	[Table("vw_aspnet_WebPartState_User")]
	public partial class vwaspnetWebPartStateUser
	{
		public virtual Guid? PathId { get; set; }
		public virtual Guid? UserId { get; set; }
		public virtual int? DataSize { get; set; }
		public virtual DateTime LastUpdatedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Game table.
    /// </summary>
	[Table("Game")]
	public partial class Game
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Title { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual int HomeScore { get; set; }
		public virtual int VisitorScore { get; set; }
		public virtual string VideoUrl { get; set; }
	}

    /// <summary>
    /// A class which represents the Statistics table.
    /// </summary>
	[Table("Statistics")]
	public partial class Statistic
	{
		[Key]
		public virtual long Id { get; set; }
		public virtual int PlayerId { get; set; }
		public virtual int GameId { get; set; }
		public virtual int _2pgm { get; set; }
		public virtual int _2pga { get; set; }
		public virtual int _3pgm { get; set; }
		public virtual int _3pga { get; set; }
		public virtual int OffReb { get; set; }
		public virtual int DefReb { get; set; }
		public virtual int Assits { get; set; }
		public virtual int Steals { get; set; }
		public virtual int Turnovers { get; set; }
		public virtual int Blockshots { get; set; }
		public virtual int Fouls { get; set; }
	}

    /// <summary>
    /// A class which represents the Article table.
    /// </summary>
	[Table("Article")]
	public partial class Article
	{
		[Key]
		public virtual int Id { get; set; }
        [Required]
        public virtual string Title { get; set; }
        [Required]
        public virtual string Text { get; set; }
        [Required]
		public virtual bool HasVideo { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string ResourceUrl { get; set; }
	}

    /// <summary>
    /// A class which represents the vw_aspnet_Applications view.
    /// </summary>
	[Table("vw_aspnet_Applications")]
	public partial class vwaspnetApplication
	{
		public virtual string ApplicationName { get; set; }
		public virtual string LoweredApplicationName { get; set; }
		public virtual Guid ApplicationId { get; set; }
		public virtual string Description { get; set; }
	}

    /// <summary>
    /// A class which represents the vw_aspnet_Users view.
    /// </summary>
	[Table("vw_aspnet_Users")]
	public partial class vwaspnetUser
	{
		public virtual Guid ApplicationId { get; set; }
		public virtual Guid UserId { get; set; }
		public virtual string UserName { get; set; }
		public virtual string LoweredUserName { get; set; }
		public virtual string MobileAlias { get; set; }
		public virtual bool IsAnonymous { get; set; }
		public virtual DateTime LastActivityDate { get; set; }
	}

    /// <summary>
    /// A class which represents the vw_aspnet_MembershipUsers view.
    /// </summary>
	[Table("vw_aspnet_MembershipUsers")]
	public partial class vwaspnetMembershipUser
	{
		public virtual Guid UserId { get; set; }
		public virtual int PasswordFormat { get; set; }
		public virtual string MobilePIN { get; set; }
		public virtual string Email { get; set; }
		public virtual string LoweredEmail { get; set; }
		public virtual string PasswordQuestion { get; set; }
		public virtual string PasswordAnswer { get; set; }
		public virtual bool IsApproved { get; set; }
		public virtual bool IsLockedOut { get; set; }
		public virtual DateTime CreateDate { get; set; }
		public virtual DateTime LastLoginDate { get; set; }
		public virtual DateTime LastPasswordChangedDate { get; set; }
		public virtual DateTime LastLockoutDate { get; set; }
		public virtual int FailedPasswordAttemptCount { get; set; }
		public virtual DateTime FailedPasswordAttemptWindowStart { get; set; }
		public virtual int FailedPasswordAnswerAttemptCount { get; set; }
		public virtual DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }
		public virtual string Comment { get; set; }
		public virtual Guid ApplicationId { get; set; }
		public virtual string UserName { get; set; }
		public virtual string MobileAlias { get; set; }
		public virtual bool IsAnonymous { get; set; }
		public virtual DateTime LastActivityDate { get; set; }
	}

    /// <summary>
    /// A class which represents the vw_aspnet_Profiles view.
    /// </summary>
	[Table("vw_aspnet_Profiles")]
	public partial class vwaspnetProfile
	{
		public virtual Guid UserId { get; set; }
		public virtual DateTime LastUpdatedDate { get; set; }
		public virtual int? DataSize { get; set; }
	}

    /// <summary>
    /// A class which represents the vw_aspnet_Roles view.
    /// </summary>
	[Table("vw_aspnet_Roles")]
	public partial class vwaspnetRole
	{
		public virtual Guid ApplicationId { get; set; }
		public virtual Guid RoleId { get; set; }
		public virtual string RoleName { get; set; }
		public virtual string LoweredRoleName { get; set; }
		public virtual string Description { get; set; }
	}

    /// <summary>
    /// A class which represents the vw_aspnet_UsersInRoles view.
    /// </summary>
	[Table("vw_aspnet_UsersInRoles")]
	public partial class vwaspnetUsersInRole
	{
		public virtual Guid UserId { get; set; }
		public virtual Guid RoleId { get; set; }
	}

}
